### ISSUE TITLE
输入部分文字后联想的搜索结果会影响下面选择搜索项

### ISSUE THREAD

**Issue by ZhangDonghui001** [BYR-Navi/BYR-Navi#29]

**Comment by ZhangDonghui001** [comment]
![qq 20170714115734](https://user-images.githubusercontent.com/20540018/28197899-7f7800de-688c-11e7-84b8-9078b9de03d1.png)

**Comment by ZhangDonghui001** [comment]
输入文字后，下面的百度，谷歌，地图，微博等都被挡住了，只有‘胖次’能直接点击到。。。

**Comment by iROCKBUNNY** [comment]
@ZhangDonghui011 你按一下`Esc`就可以了。
