### ISSUE TITLE
关于新版北邮人导航搭建

### ISSUE THREAD

**Issue by XIGUAXIE** [BYR-Navi/BYR-Navi#30]
你好，我是一个小白，新接触此类源码不太懂得ruby，想请问一下如何用此源码快速的搭建一个网站即搭建方法。烦请您告知。谢谢。

**Comment by iROCKBUNNY** [comment]
@XIGUAXIE 您好！感谢提问，你需要一下相关准备：
1. 阅读Jekyll开发文档：http://jekyllrb.com/
2. 具备HTML/CSS/JS编程基础
3. 了解Semantic UI等其它依赖包的开发文档：https://semantic-ui.com/

祝你好运！
