### ISSUE TITLE
不知道如何正确配置

### ISSUE THREAD

**Issue by enalpha** [BYR-Navi/BYR-Navi#31]
--- layout: default home: true --- {% for section in site.data.links %}
{% if forloop.first %}{% include page_loading_progress_bar.html %}{% endif %}
{% for item in section.categories %}
{{ item.category }}
{% for link in item.links %}{% if link.icon %}{% endif %}{{ link.name }}{% endfor %}
{% endfor %}
{% endfor %}

复制到我的虚拟空间之后打开首页就显示源码，不知道如何正确配置。

**Comment by iROCKBUNNY** [comment]
@enalpha 
你是直接当做静态文件来处理吧。

需要先用Jekyll把模板文件渲染成静态文件，一般渲染完成后会保存在`_site`文件夹，把这个文件夹里面的内容复制到你所谓的“虚拟空间”中应该就可以了。

或者，你使用GitHub Pages来托管网站，GitHub Pages已经继承了Jekyll的引擎，直接用Jekyll代码即可。

当然，GitHub Pages也支持直接上传静态文件，也就是直接把Jekyll渲染得到的`_site`文件夹中的内容放在GitHub Pages也是可以的。

详情请参考：
- Jekyll: http://jekyllrb.com/
- GitHub Pages: https://pages.github.com/
