### ISSUE TITLE
Add `autofocus` attribute in the search `<input>` tag

### ISSUE THREAD

**Issue by wyj1026** [BYR-Navi/BYR-Navi#32]
When a user open the page, it will be better if the cursor is focused on the search form, so
the user can just type the thing that they want to search instead of clicking the form first. I suggest to add  `autofocus` attribute in the search `<input>` tag.

https://www.w3schools.com/tags/att_input_autofocus.asp

HTML5 Syntax:
```
<input autofocus>
```

XHTML Syntax:
```
<input autofocus="autofocus">
```

**Comment by iROCKBUNNY** [comment]
@wyj1026 Thanks for your advice! Your suggested feature will be implemented in the next PR, hopefully.

**Comment by iROCKBUNNY** [comment]
Fixed in #33
