### ISSUE TITLE
关于搜索结果。。

### ISSUE THREAD

**Issue by KB5201314** [BYR-Navi/BYR-Navi#38]
百度搜索结果为什么不使用https协议的，百度搜索不是已经支持全站 https了嘛🙂

**Comment by KB5201314** [comment]
emmm难道我看错了？刚才访问的时候都是http，现在好像已经是https了

**Comment by KB5201314** [comment]
又出现http的情况了(⊙﹏⊙)，好像是百度有时候会自己把http改到https

**Comment by iROCKBUNNY** [comment]
是的，确实是这样，无需多虑。
