### ISSUE TITLE
搜索框内的文字一直处于全选状态的情况

### ISSUE THREAD

**Issue by KB5201314** [BYR-Navi/BYR-Navi#39]
搜索框里面输入内容以后，如果点击网页其他地方，让搜索框失去焦点，再点击搜索框后，搜索框文字一直处于全选状态，除非按方向键才出现光标
环境：
Windows10
Microsoft Edge 40.15063.0.0
实测Firefox出现同样的情况

**Comment by iROCKBUNNY** [comment]
故意这样设计的，并不是问题。

**Comment by KB5201314** [comment]
？？那要修改起来岂不是很麻烦

**Comment by iROCKBUNNY** [comment]
@KB5201314 你可以fork走自己研究一下相关的代码
