### ISSUE TITLE
如何配置analytics（piwik）

### ISSUE THREAD

**Issue by XIGUAXIE** [BYR-Navi/BYR-Navi#40]
你好，如何配置piwik正确进行访客呢？

**Comment by iROCKBUNNY** [comment]
@XIGUAXIE 需要部署一个Matomo服务，参考一下Matomo的教程：https://matomo.org/

**Comment by XIGUAXIE** [comment]
已经部署Matomo，只需要正确修改token及回调地址就可以了吗？

**Comment by XIGUAXIE** [comment]
要将统计代码加入哪里？

**Comment by iROCKBUNNY** [comment]
@XIGUAXIE pull到最新版本的话，应该是可以的。如果出现问题，Matomo那边的配置根据浏览器报错相应调教一下。

**Comment by XIGUAXIE** [comment]
获取不到今日访客数是怎么回事。在线访客及昨日访客可以获取。

**Comment by iROCKBUNNY** [comment]
@XIGUAXIE 没有具体的东西我也不知道怎么回事。你把网站地址或者代码发上来？
