### ISSUE TITLE
网页a标签target定义失效，点击链接无法打开新窗口

### ISSUE THREAD

**Issue by XIGUAXIE** [BYR-Navi/BYR-Navi#42]
网页a标签target定义失效，点击链接无法打开新窗口！
不知道此情况下跳转至目标站之后目标站无法统计到来路是不是由于该原因。

**Comment by XIGUAXIE** [comment]
https://www.yab-dh.com

**Comment by iROCKBUNNY** [comment]
@XIGUAXIE 具体是哪个a标签的target定义失效？

**Comment by XIGUAXIE** [comment]
网页中链接不是定义了_blank吗？但是都没法从新窗口打开的。

**Comment by iROCKBUNNY** [comment]
@XIGUAXIE 我用的Chrome浏览器打开后是正常的，可否提供具体的案例？

**Comment by XIGUAXIE** [comment]
抱歉是我的疏忽，换个浏览器就解决了，我在手机端用的是UC浏览器，uc不会在新窗口打开。谢谢。
