### ISSUE TITLE
百度query suggestions不支持https，出错

### ISSUE THREAD

**Issue by enalpha** [BYR-Navi/BYR-Navi#43]
经过debug发现，百度的js不支持https的格式，导致获取query suggestions出错。因为我的网站是默认全局https的，有没有办法修正？

**Comment by iROCKBUNNY** [comment]
@enalpha 目前没有，去找一下支持https的替代方案吧。

**Comment by iROCKBUNNY** [comment]
@enalpha 可以参考一下这个：https://www.jianshu.com/p/1520579fefc7
