### ISSUE TITLE
Python version of BYR-Navi

### ISSUE THREAD

**Issue by fundviz** [BYR-Navi/BYR-Navi#45]
I use BYR-Navi as my personal navigation website and I really like its design concept. But I am not familiar with Jekyll. Thus, I modified it with Python and Plotly DASH. I have already put your BYR-Navi info under the bottom of the website for copyright purpose. 
Hope you won't mind it.

# Demo
Link: [ChaQi.net](http://www.chaqi.net)
Github: [github](https://github.com/fundviz/chaqi_navi)

![](https://raw.githubusercontent.com/fundviz/chaqi_navi/master/demo.png)

**Comment by iROCKBUNNY** [comment]
@fundviz Hi! Many thanks for your affection and affirmation of BYR-Navi and the efforts within. Unfortunately, your demo seems to be failed, which might be result of some internal errors on your server. I am looking forward to seeing a actively live version of your website soon. Good luck!

**Comment by iROCKBUNNY** [comment]
@fundviz By the way, I read your code and found out you are trying to use Flask. If you are deploy a Flask app on Ubuntu or other Linux/UNIX-like operating systems, I would recommend you to use `Flask (with Jinjia) + uWSGI + NGINX` as a deployment stack on a production server, according to my experiences.

**Comment by fundviz** [comment]
you are right, I feel like FLASK+JINJA2 will be more suitable than DASH framework for the lightweight web. I realized DASH will load too much unnecessary JS files to serve its framework, which is not a elegant way to display a website. Thanks for your advice. I appreciate it.

**Comment by iROCKBUNNY** [comment]
@fundviz For my point of view, if you understand Jinja templating philosophy, it won't be any obstacles to adopt the [Liquid](https://shopify.github.io/liquid/) templating engine, which is used by Jekyll. Their syntaxes are almost the same. Once you understand how light-weight to build a static website using Jekyll, you can simply upload the generated site files under `_site` directory to your server web root and host it using NGINX, since NGINX is best known for its outstanding static file performance.

**Comment by fundviz** [comment]
wow, I didnt even know they have so much in common.  I like the way Jekyll delivers the static HTML but sometimes feel like I need a website more than just static HTML. I mainly use DASH framework for my data visualization and never use FLASK before. But I feel like DASH and FLASK are pretty much the same somehow.  Actually, I have made some changes such as instant internal search, tooltips on your Jekyll-based  BYR-Navi before for my another navigation website. Here is the link, www.smzdcha.com.

**Comment by iROCKBUNNY** [comment]
@fundviz Precisely, a static website is not an equivalent to a website of pure HTML pages. In my opinion, the major differences between a static website and a non-static website are the way of the content delivery and how the contents are stored and rendered.

According to Wikipedia:
> A static web page (sometimes called a flat page/stationary page) is a web page that is delivered to the user exactly as stored, in contrast to dynamic web pages which are generated by a web application.
>
> Consequently, a static web page displays the same information for all users, from all contexts, subject to modern capabilities of a web server to negotiate content-type or language of the document where such versions are available and the server is configured to do so.

and

> A server-side dynamic web page is a web page whose construction is controlled by an application server processing server-side scripts. In server-side scripting, parameters determine how the assembly of every new web page proceeds, including the setting up of more client-side processing.
>
> A client-side dynamic web page processes the web page using HTML scripting running in the browser as it loads. JavaScript and other scripting languages determine the way the HTML in the received page is parsed into the Document Object Model, or DOM, that represents the loaded web page. The same client-side techniques can then dynamically update or change the DOM in the same way.

Hence, you can still do some dynamic tricks with JS to the so-called static website.

**Comment by fundviz** [comment]
Thanks for the clarification. I have learned FLASK for the whole day yesterday and realized there are so much in common between FLASK and JEKYLL. I also feel like Flask is more efficient and handy to build up a website like BYR-Navi as you said.  I am so glad to have such a discussion with you !
