### ISSUE TITLE
请问北邮人在宝塔下怎么安装？

### ISSUE THREAD

**Issue by JusufUs** [BYR-Navi/BYR-Navi#49]
求大佬发个教程

**Comment by iROCKBUNNY** [comment]
@JusufUs I am not familiar with `BaoTa Panel`, but I can give you some hints. However, if you do not understand the basic staff, my advice might not do the favor for you. 

1. First, you have to build the entire website to obtain the static site files.
2. After that, you can follow the `BaoTa` documentations to build a static website using those files.
