### ISSUE TITLE
为什么北邮人导航主页现在搜索框打字不好按回车和鼠标来确定搜索呢?

### ISSUE THREAD

**Issue by lovemc13140** [BYR-Navi/BYR-Navi#55]
https://byr-navi.com/ 就是这个网址 搜索框里打好字 按了回车键和鼠标点搜索什么反应都没有  麻烦问下是啥原因? 还挺喜欢这个导航主页的

**Comment by iROCKBUNNY** [comment]
Fixed in ddf1168f1d0fc4f01551ee279f67ec7932e12943
