### ISSUE TITLE
[Unexpected Behavior]Error occurs after disabling Matomo analytics

### ISSUE THREAD

**Issue by lwd-temp** [BYR-Navi/BYR-Navi#59]
According to [analytics.yml](https://github.com/BYR-Navi/BYR-Navi/blob/961a97f755065299b59a609f9e06f72b0235f0f7/_data/analytics.yml#L8) & [_includes/analytics.html](https://github.com/BYR-Navi/BYR-Navi/blob/961a97f755065299b59a609f9e06f72b0235f0f7/_includes/analytics.html#L11), it seems that if `site_id` is blank,  Matomo analytics will be disabled.
Sadly,`analyticsAPI` defined [here](https://github.com/BYR-Navi/BYR-Navi/blob/961a97f755065299b59a609f9e06f72b0235f0f7/_includes/analytics.html#L13) is used by several JavaScripts ( [common.js](https://github.com/BYR-Navi/BYR-Navi/blob/961a97f755065299b59a609f9e06f72b0235f0f7/assets/js/common.js#L23) & [home.js](https://github.com/BYR-Navi/BYR-Navi/blob/961a97f755065299b59a609f9e06f72b0235f0f7/assets/js/home.js#L36) ).Simply leave it blank will cause errors which will stop necessary JavaScripts from working.
It seems that this is an unexpected behavior.

根据 [analytics.yml](https://github.com/BYR-Navi/BYR-Navi/blob/961a97f755065299b59a609f9e06f72b0235f0f7/_data/analytics.yml#L8) 和 [_includes/analytics.html](https://github.com/BYR-Navi/BYR-Navi/blob/961a97f755065299b59a609f9e06f72b0235f0f7/_includes/analytics.html#L11), 看起来似乎当`site_id`留空时,  Matomo统计相关代码会被自动移除。
不幸的是，变量`analyticsAPI`（定义在[这里](https://github.com/BYR-Navi/BYR-Navi/blob/961a97f755065299b59a609f9e06f72b0235f0f7/_includes/analytics.html#L13)）被一些脚本 ( [common.js](https://github.com/BYR-Navi/BYR-Navi/blob/961a97f755065299b59a609f9e06f72b0235f0f7/assets/js/common.js#L23) 和 [home.js](https://github.com/BYR-Navi/BYR-Navi/blob/961a97f755065299b59a609f9e06f72b0235f0f7/assets/js/home.js#L36) )使用。直接留空会发生错误并阻止一些基于js的功能。
这似乎是一个未预料到的行为。

**Comment by iROCKBUNNY** [comment]
Fixed by https://github.com/BYR-Navi/BYR-Navi/commit/3c612f3ac4642f2c3e3b1c130ed5b450a90a9ab7.
